//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BesicApp1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Demo1Entities : DbContext
    {
        public Demo1Entities()
            : base("name=Demo1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CITY_MASTER> TBL_CITY_MASTER { get; set; }
        public virtual DbSet<TBL_COUNTRY_MASTER> TBL_COUNTRY_MASTER { get; set; }
        public virtual DbSet<TBL_ERROR_LOG> TBL_ERROR_LOG { get; set; }
        public virtual DbSet<TBL_PAGE_MASTER> TBL_PAGE_MASTER { get; set; }
        public virtual DbSet<TBL_REGISTRATION_MASTER> TBL_REGISTRATION_MASTER { get; set; }
        public virtual DbSet<TBL_RIGHTS_MASTER> TBL_RIGHTS_MASTER { get; set; }
        public virtual DbSet<TBL_ROLE_MASTER> TBL_ROLE_MASTER { get; set; }
        public virtual DbSet<TBL_STATE_MASTER> TBL_STATE_MASTER { get; set; }
        public virtual DbSet<TBL_USER_MASTER> TBL_USER_MASTER { get; set; }
    }
}
