//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BesicApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COUNTRY_MASTER
    {
        public int COUNTRY_ID { get; set; }
        public string COUNTRY_NAME { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public string CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
    }
}
