//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BesicApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ERROR_LOG
    {
        public long REFID { get; set; }
        public string ERRORMSG { get; set; }
        public string ERRORTYPE { get; set; }
        public string ERRORLINE { get; set; }
        public string ERRORFROM { get; set; }
        public string ERRORPAGE { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
    }
}
