//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BesicApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REGISTRATION_MASTER
    {
        public int REG_ID { get; set; }
        public string F_NAME { get; set; }
        public string M_NAME { get; set; }
        public string L_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public Nullable<int> STATE_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public string ADDRESS_1 { get; set; }
        public string PHONE_1 { get; set; }
        public string GENDER { get; set; }
        public string PHOTO { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
    }
}
